### ISSUE TITLE
Prepis zo záznamu zo stretnutia

### ISSUE THREAD

**Issue by elratondesusi** [TIS2019-FMFI/parking-system#1]
Prepisat stretnutie. Poslat ho na schvalenie zadavatelovi.

**Comment by elratondesusi** [comment]
Prepisana 1. aj 2. polovica.

**Comment by marek98** [comment]
Prepis odoslaný a prijatie potvrdené p. Vargom. Zatváram, Marek.

**Comment by pavelpetrovic** [comment]
vdaka, este to potom na stretnuti dolozte, aby som si to zaznacil.
