### ISSUE TITLE
UML state/UML sequence diagram

### ISSUE THREAD

**Issue by elratondesusi** [TIS2019-FMFI/parking-system#11]

**Comment by marek98** [comment]
Prvotný návrh UML state diagramu pre entitu **Box** (Vytvorenie záznamu o parkovaní).
Chcel by som sa spýtať p.@pavelpetrovic, či je to dobré, poprípade, aké sú k tomu výhrady, aby som vedel diagram prepracovať a v podobnom duchu ich vytvoriť aj pre ostatné entity.

<img width="1276" alt="UML state diagram" src="https://user-images.githubusercontent.com/16921364/69151571-27332400-0adb-11ea-9916-c2b888c8b8d5.png">

**Comment by pavelpetrovic** [comment]
poprosim stavovy diagram, ktory zachytava stavy nejakej entity, toto mozete prerobit na activity diagram, ak chcete.

**Comment by marek98** [comment]
<img width="943" alt="stavový diagram" src="https://user-images.githubusercontent.com/16921364/74132616-3c55b580-4be7-11ea-9efc-3b08e829c5bc.png">
