### ISSUE TITLE
Zápisnica zo stretnutia skupiny 29. 10. 

### ISSUE THREAD

**Issue by marek98** [TIS2019-FMFI/parking-system#15]
Marek spíše zápisnicu zo stretnutia skupiny, ktoré sa konalo 29. 10. 2019

**Comment by marek98** [comment]
Zápisnicu zo stretnutia skupiny, ktoré sa konalo 29. 10. 2019 nájdete **[na tomto linku](https://github.com/TIS2019-FMFI/parking-system/wiki/Zápisnica-zo-stretnutia-29.10.-2019)**.

**Comment by pavelpetrovic** [comment]
zápisnicu zo stretnutia prosím vždy píšte priamo na stretnutií. ďakujem.
