### ISSUE TITLE
Katalog poziadaviek

### ISSUE THREAD

**Issue by elratondesusi** [TIS2019-FMFI/parking-system#2]

**Comment by pavelpetrovic** [comment]
mailom som dostal prvy navrh KP (prikladam)
 - prosim doplnit chybajuce state
 - niekde treba vysvetlit, ako funguje evidencia obsadenosti
   napr. ak by som mal uhadnut, co je "cas odchodu" z poziadavky 3.3.1.2, tak by som si neporadil, lebo na jednej strane to vyzera, ze je to nieco evidovane len po dobu parkovania, na druhej strane to vyzera ako nieco evidovane do historie parkovania
- KP by mal byt natolko podrobne vystizny, ze formulacie ako "označiť na dobu" treba vysvetlit - moze to byt v rozsahu viacerych dni? Je cas s presnostou na minuty alebo pol hodiny?
- 3.3.1.3.  zapozicanie - nie je mozne tam zaznacit ktora firma alebo aspon dat nejaku poznamku?
- 3.3.1.4. mozete prosim upresnit ake informacie?
- v 3.3.1.2 sa nepise "odkedy" v zobr. informaciach o rozkliknutom boxe, ale v 3.3.1.5 sa to uvadza
- v 3.3.1.5. by asi nemalo byt dokedy, lebo to sa zaznacuje automaticky uz len do historie, toto treba zdoraznit
- v 3.3.1.6. je mozne fotku nahrat iba pocas zleho parkovania alebo aj dodatocne? upravit.
- 3.3.1.7 - napr. by sa mohol vytvarat novy priecinok, v ktorom sa spravi .CSV subor a tiez sa tam nakopiruju fotky; polozky statistik prosim podrobne definovat
 niekde sa ma urcit odkedy-dokedy statistika
 niekde by sa malo dat nastavovat ktore miesta patria urcitej firme - toto by sa malo evidovat aj do historie
 v statistike o vyuziti miest asi treba nejak zohladnovat priebezne poziciavanie 

zvazte prosim doplnit:
 - rozlozenie boxov na parkovisku by sa mohlo konfigurovat v subore  ID, x1,y1,x2,y2
 - doplnte ci aplikacia bude reagovat na zmeny velkosti okna a ak nie tak treba stanovit
   minimalne pozadovane rozlisenie displeja na ktorom sa bude dat pouzivat
 - upresnit proces exportu - v samostatnom okne sa konfiguruje? spusta sa nejakym tlacidlom?
 - asi by system mal evidovat zoznam platnych firiem a moznost zadat novu do zoznamu a pri zadavani firmy dat vybrat zo zoznamu, KP by to mal zachytit
 - ci aplikacia robi log operacii (nejaky jednoduchy textovy subor)






[214053.docx](https://github.com/TIS2019-FMFI/parking-system/files/3749315/214053.docx)

**Comment by pavelpetrovic** [comment]
k novej verzii:
2.2. je trochu strucne, nedozvedam sa z toho, co to ma vlastne robit
2.3. prosim tiez rozvit - bezi iba naraz jeden pouzivatel na jednom pocitaci, nemusi sa prihlasovat
3.1.1.1  komplexne nerozumiem
1.3 nadpis sa predbehol
1.3.2. zbytocny nadpis
1.3.3 uz patri do non-fun R
1.3.2.2 nerozumiem 1) co sa zobrazi  2) co sa da nastavit  3) ako to funguje s nahratim fotky
nie je jasne, ako system zisti aky druh parkovania to je, chyba popis co vsetko v tom okienku je a co sa da vyberat (v ratane prenajmov a zapozacani)
do slovnika pojmov vysvetlite 
- prenajate miesto
- zapozicane miesto
z dokumentu nie je zrejmy suvis medzi 1.3.2.2 a 1.3.2.3 (v minutach?)
- export prosim popisat presne ake stlpce a ake subory

**Comment by pavelpetrovic** [comment]
vyjadrite sa co je v konfiguracnom subore

**Comment by pavelpetrovic** [comment]
tiez pridat prosim info o tom, ze system eviduje firmy a ako sa pridavaju (pripadne rusia?)
dakujem

**Comment by marek98** [comment]
> tiez pridat prosim info o tom, ze system eviduje firmy a ako sa pridavaju (pripadne rusia?)
> dakujem

Editovaniu nájomníkov sa venujeme v issue #13. Táto issue obsahuje prvotný návrh. Ďalšie zmeny a návrhy budeme komunikovať tam.

**Comment by elratondesusi** [comment]
Najnovšia verzia KP, chýba export a filtre pre štatistiku.
[Parkovací systém - katalóg požiadaviek - pracovná verzia (doplnené).docx](https://github.com/TIS2019-FMFI/parking-system/files/3788324/Parkovaci.system.-.katalog.poziadaviek.-.pracovna.verzia.doplnene.docx)

**Comment by elratondesusi** [comment]
[Parkovaci.system.-.katalog.poziadaviek.-.pracovna.verzia.doplnene (1).docx](https://github.com/TIS2019-FMFI/parking-system/files/3803373/Parkovaci.system.-.katalog.poziadaviek.-.pracovna.verzia.doplnene.1.docx)
@gyurcsovicsova @marek98

**Comment by elratondesusi** [comment]
[Parkovaci.system.-.katalog.poziadaviek.-.pracovna.verzia.doplnene (1).docx](https://github.com/TIS2019-FMFI/parking-system/files/3808778/Parkovaci.system.-.katalog.poziadaviek.-.pracovna.verzia.doplnene.1.docx)
- najnovsi, treba upravit odkazovanie sa na body

**Comment by elratondesusi** [comment]
[Parkovaci.system.-.katalog.poziadaviek.docx](https://github.com/TIS2019-FMFI/parking-system/files/3813862/Parkovaci.system.-.katalog.poziadaviek.docx)

**Comment by elratondesusi** [comment]
[Parkovaci.system.-.katalog.poziadaviek_doplnene.docx](https://github.com/TIS2019-FMFI/parking-system/files/3855455/Parkovaci.system.-.katalog.poziadaviek_doplnene.docx)
@pavelpetrovic - prosím skontrolovať. Je doplnená časť o konfigurácií parkoviska (bod. 3.2.21.) a o štatistike (body 3.2.19. a 3.2.20.). Vďaka

**Comment by elratondesusi** [comment]
[Parkovaci.system.-.katalog.poziadaviek_FINAL.docx](https://github.com/TIS2019-FMFI/parking-system/files/3863296/Parkovaci.system.-.katalog.poziadaviek_FINAL.docx)
@pavelpetrovic zapracované pripomienky zo včerajšieho stretnutia. Prosíme skontrolovať.
 Ďakujeme
