### ISSUE TITLE
nákresy GUI

### ISSUE THREAD

**Issue by gyurcsovicsova** [TIS2019-FMFI/parking-system#3]

**Comment by gyurcsovicsova** [comment]
![GUI_nastavenia_box](https://user-images.githubusercontent.com/47821684/67642791-c49d9c80-f90f-11e9-9609-e55d835b2fd3.png)
![GUI_nastavenia](https://user-images.githubusercontent.com/47821684/67642792-c49d9c80-f90f-11e9-93c6-2ccb5657340f.png)
![GUI_box](https://user-images.githubusercontent.com/47821684/67642793-c49d9c80-f90f-11e9-90af-16897a68a4d8.png)
![GUI](https://user-images.githubusercontent.com/47821684/67642794-c49d9c80-f90f-11e9-8028-7ee5ce3927dd.png)

**Comment by gyurcsovicsova** [comment]
pridávam upravené návrhy GUI
![GUI_nastavenia (1)](https://user-images.githubusercontent.com/47821684/68092491-04becb00-fe8c-11e9-944c-76ff7995fd5e.png)
![GUI_nastavenia_box (1)](https://user-images.githubusercontent.com/47821684/68092492-08eae880-fe8c-11e9-97b6-d5e95f8ab340.png)

**Comment by pavelpetrovic** [comment]
v navrhu ui by mali byt vsetky okienka/dialogy/stranky v takej podobe, ak ich navrhujete do aplikacie - t.j. tam, kde su editovacie boxy budu editovacie boxy, vsetky podrobnosti, ktore sa daju v dialogoch zadat, komplet vsetko ako planujete naprogramovat. zatial to je snad len pracovna verzia, ktora sa este vyvija?

**Comment by gyurcsovicsova** [comment]
![Untitled Diagram (1)](https://user-images.githubusercontent.com/47821684/68565515-0e2fd080-0454-11ea-80f3-a8758589f93f.png)
![Výber miesta](https://user-images.githubusercontent.com/47821684/68565531-1982fc00-0454-11ea-8a16-196892cc44a5.png)
![Zruš miesto](https://user-images.githubusercontent.com/47821684/68565549-299adb80-0454-11ea-9eaf-23ec27add854.png)
![Upozornenie](https://user-images.githubusercontent.com/47821684/68565555-2d2e6280-0454-11ea-8437-0420c6974dcd.png)
![Firmy](https://user-images.githubusercontent.com/47821684/68565562-34557080-0454-11ea-8358-a2305a6cc39b.png)

**Comment by gyurcsovicsova** [comment]
![Zruš miesto (1)](https://user-images.githubusercontent.com/47821684/69014898-183f5b00-098f-11ea-8792-683204547cca.png)
![Výber miesta (1)](https://user-images.githubusercontent.com/47821684/69014900-1d040f00-098f-11ea-8c13-d4556222e2d5.png)

**Comment by gyurcsovicsova** [comment]
![statistika (1)](https://user-images.githubusercontent.com/47821684/69516651-9208b300-0f52-11ea-8f3b-79576040b140.png)
![Parkovisko_plocha](https://user-images.githubusercontent.com/47821684/69516663-9d5bde80-0f52-11ea-9dfc-d05da611ebc0.png)

**Comment by pavelpetrovic** [comment]
prosim do boxov pridat text:
 - oznacenie boxu
 - firma

upravte "Windows Title"

v zozname firiem zobrazovat ID firmy aby sa dalo podla neho robit config
