### ISSUE TITLE
Vybratie technológie pre projekt

### ISSUE THREAD

**Issue by marek98** [TIS2019-FMFI/parking-system#4]
Java vs Python? 
SQLite?

Na stretnutí 22. 10. by sme sa na to mohli pozrieť.

Za mňa osobne navrhujem Python + PyQt (ako knižnicu na grafiku). Na ukladanie dát by sme mohli použiť SQLite, ktorý slúži ako lokálna databáza.

**Comment by marek98** [comment]
Na stretnutí s p. Petrovičom 28. 10. 2019 sme náš návrh prekonzultovali a PyQT nám nebolo odporučené.
P. Petrovič nám povedal, že projekt našeho rozsahu by v pohode stačil Python + Tkinter alebo Java + JavaFX.

**Comment by pavelpetrovic** [comment]
Rozhodnutie je samozrejme na Vás, ak si vyberiete pyQT, bude to pyQT.
Len si myslím, že si 1) ušetríte robotu, ak sa nebudete musiet učiť nový framework a 2) výsledok bude mať menšie nároky na veľkosť inštalácie.

**Comment by elratondesusi** [comment]
Finálny výber padol na Python v kombinácii s knižnicami Tkinter a SQLite.
