### ISSUE TITLE
Dátový model

### ISSUE THREAD

**Issue by elratondesusi** [TIS2019-FMFI/parking-system#8]
Podrobný dátový model perzistentných údajov, formátov súborov, komunikačných protokolov.

**Comment by marek98** [comment]
Prvý návrh dátového modelu, ktorý obsahuje popis pre tabuľky: Záznam o parkovaní, Box, Firma.
Chcel by som sa spýtať p. @pavelpetrovic, je to dobre, alebo by mal dátový model vyzerať nejako ináč?

<img width="802" alt="Snímek obrazovky 2019-11-05 v 12 55 11" src="https://user-images.githubusercontent.com/16921364/68205857-954ff500-ffcb-11e9-9877-e5592bc5bf8d.png">

**Comment by pavelpetrovic** [comment]
zvazte ci nepouzit tuto myslienku
[priklad_konfiguracie_parkoviska.txt](https://github.com/TIS2019-FMFI/parking-system/files/3830317/priklad_konfiguracie_parkoviska.txt)

**Comment by marek98** [comment]
- V databáze budeme uchovávať **záznamy o parkovaní** a **zoznam firiem**. Informácie o boxoch z nej teda vypadnú.
- Konfigurácia rozloženia bude v konfiguračnom súbore, ktorý sa bude volať **"konfig_parkoviska.txt"**. V ňom budú všetky informácie, ktoré sú potrebné na to, aby sa parkovisko správne vykreslilo.
- Formát súboru: <ID_boxu : int>  <označenie_boxu : string>  <X : double>  <Y : double>  <šírka: double>  <výška : double>  <ID_firmy : int>  <pre_vozíčkárov : boolean>
- Jednotlivé hodnoty budú v súbore oddelené bodkočiarkou **;**
- Hodnoty pre X, Y, šírku a výšku budú v percentách. Ide o to, že s touto mierkou sa bude dobre pracovať pri aplikácií s premenlivým rozlíšením.

- Príklad takého súboru: [**konfig_parkoviska_ukazka.txt**](https://github.com/TIS2019-FMFI/parking-system/files/3864270/konfig_parkoviska_ukazka.txt)


Chcel by som sa spýtať p.@pavelpetrovic, či je to dobre a či dátový model môže vyzerať takto.

**Comment by elratondesusi** [comment]
Dátový model schválený.
