### ISSUE TITLE
 UML component diagram

### ISSUE THREAD

**Issue by elratondesusi** [TIS2019-FMFI/parking-system#9]

**Comment by gyurcsovicsova** [comment]
![Untitled Diagram (2)](https://user-images.githubusercontent.com/47821684/69516690-b5cbf900-0f52-11ea-988e-4ef7b4447a4a.png)

**Comment by pavelpetrovic** [comment]
zaznamy ma asi zmysel spojit do jedneho,
zobrazenie parkoviska si asi zasluzi podkomponent sprava notifikacii, s ktorym interaguje alarmovac.

**Comment by gyurcsovicsova** [comment]
![Untitled Diagram (2) (1) (1)](https://user-images.githubusercontent.com/47821684/70868808-883c0380-1f84-11ea-8532-caa33d7d2168.png)
